"""create collection_items table

Revision ID: 10720bf9574b
Revises: 4498aaa41520
Create Date: 2025-12-16 21:27:29.342260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10720bf9574b'
down_revision: Union[str, Sequence[str], None] = '4498aaa41520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_name', sa.String(length=100), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('qty_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labour_per_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('coolie_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transport_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_labour', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['farmer_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_id'), 'collection_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_items_id'), table_name='collection_items')
    op.drop_table('collection_items')
    # ### end Alembic commands ###
