"""create settlements table

Revision ID: 146c7874609c
Revises: 6f3a57551131
Create Date: 2025-12-16 21:34:11.913866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146c7874609c'
down_revision: Union[str, Sequence[str], None] = '6f3a57551131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.DATE(), nullable=False),
    sa.Column('date_to', sa.DATE(), nullable=False),
    sa.Column('total_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_labour', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_coolie', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_transport', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_deducted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_table('settlements')
    # ### end Alembic commands ###
