"""update saala transaction amounts to numeric types

Revision ID: 21f57d12bdfd
Revises: b096f5878979
Create Date: 2026-01-23 00:19:59.643662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21f57d12bdfd'
down_revision: Union[str, Sequence[str], None] = 'b096f5878979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silk_ledger_customer_id'), table_name='silk_ledger_entries')
    op.drop_index(op.f('ix_silk_ledger_date'), table_name='silk_ledger_entries')
    op.drop_index(op.f('ix_silk_ledger_entries_id'), table_name='silk_ledger_entries')
    op.drop_index(op.f('ix_silk_ledger_vendor_id'), table_name='silk_ledger_entries')
    op.drop_table('silk_ledger_entries')
    op.drop_index(op.f('ix_silk_collections_date'), table_name='silk_collections')
    op.drop_index(op.f('ix_silk_collections_id'), table_name='silk_collections')
    op.drop_index(op.f('ix_silk_collections_vendor_id'), table_name='silk_collections')
    op.drop_table('silk_collections')
    op.alter_column('saala_customers', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('saala_customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('saala_customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('saala_transactions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('saala_transactions', sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('saala_transactions', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('saala_transactions', 'qty',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('saala_transactions', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('saala_transactions', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('saala_transactions', 'paid_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('saala_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('saala_transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('saala_transactions', 'item_code')
    op.drop_column('saala_transactions', 'remarks')
    op.drop_column('saala_transactions', 'item_name')
    op.drop_index(op.f('ix_silk_phy_dig_entries_date'), table_name='silk_physical_digital_entries')
    op.drop_index(op.f('ix_silk_phy_dig_entries_vendor_id'), table_name='silk_physical_digital_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_silk_phy_dig_entries_vendor_id'), 'silk_physical_digital_entries', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_silk_phy_dig_entries_date'), 'silk_physical_digital_entries', ['date'], unique=False)
    op.add_column('saala_transactions', sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('saala_transactions', sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('saala_transactions', sa.Column('item_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('saala_transactions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('saala_transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('saala_transactions', 'paid_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('saala_transactions', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('saala_transactions', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('saala_transactions', 'qty',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('saala_transactions', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('saala_transactions', 'balance')
    op.drop_column('saala_transactions', 'description')
    op.alter_column('saala_customers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('saala_customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('saala_customers', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.create_table('silk_collections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('credit_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('cash_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('upi_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('total_entered', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('ledger_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('difference', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('MATCHED', 'MISMATCH', name='collectionstatus'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('silk_collections_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('silk_collections_vendor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('silk_collections_pkey'))
    )
    op.create_index(op.f('ix_silk_collections_vendor_id'), 'silk_collections', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_silk_collections_id'), 'silk_collections', ['id'], unique=False)
    op.create_index(op.f('ix_silk_collections_date'), 'silk_collections', ['date'], unique=False)
    op.create_table('silk_ledger_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('kg', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['farmers.id'], name=op.f('silk_ledger_entries_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('silk_ledger_entries_vendor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('silk_ledger_entries_pkey'))
    )
    op.create_index(op.f('ix_silk_ledger_vendor_id'), 'silk_ledger_entries', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_silk_ledger_entries_id'), 'silk_ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_silk_ledger_date'), 'silk_ledger_entries', ['date'], unique=False)
    op.create_index(op.f('ix_silk_ledger_customer_id'), 'silk_ledger_entries', ['customer_id'], unique=False)
    # ### end Alembic commands ###
