"""create silk physical digital entries table

Revision ID: 47875aaa76dd
Revises: def789ghi012
Create Date: 2026-01-22 21:07:56.179412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47875aaa76dd'
down_revision: Union[str, Sequence[str], None] = 'def789ghi012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - create silk physical digital entries table."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create silk_physical_digital_entries table
    op.create_table('silk_physical_digital_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DATE(), nullable=False),
        sa.Column('physical_kg', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
        sa.Column('physical_rate', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
        sa.Column('physical_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
        sa.Column('digital_kg', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
        sa.Column('digital_rate', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
        sa.Column('digital_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
        sa.Column('total_kg', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
        sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_silk_phy_dig_entries_vendor_id', 'silk_physical_digital_entries', ['vendor_id'])
    op.create_index('ix_silk_phy_dig_entries_date', 'silk_physical_digital_entries', ['date'])
    op.create_index(op.f('ix_silk_physical_digital_entries_id'), 'silk_physical_digital_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vehicles_vendor_id_vehicle_number', 'vehicles', type_='unique')
    op.drop_index('ix_vehicles_vendor_id', table_name='vehicles')
    op.alter_column('settlements', 'void_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('settlements', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.drop_index('ix_farmers_vendor_id', table_name='farmers')
    op.drop_constraint('uq_farmer_groups_vendor_id_name', 'farmer_groups', type_='unique')
    op.drop_index('ix_farmer_groups_vendor_id', table_name='farmer_groups')
    # ### end Alembic commands ###
